### ISSUE TITLE
**Student Skills Checklist**

### ISSUE THREAD

**Issue by spooketti** [spooketti/studentCSA#2]
**Student Skills Checklist**

- [X] **Laptop Verification or Cloud Workspace**
  - Rank: 4
  - Notes: verification by Linux commands notebook

- [X] **VSCode**
  - Rank: 4
  - Notes: live change code, commit, make, run localhost, test, debug

- [X] **Show VSCode GitLens**
  - Rank: 4
  - Notes: verify commits, show change, comments, reset to commit, run on old commit

- [X] **GitHub cloud repo**
  - Rank: 4
  - Notes: live push change, verify id, review profile

- [X] **GitHub Pages Actions**
  - Rank: 4
  - Notes: review runs and verify runtime, receive demo

- [X] **Hacks Tools & Equipment Play**
  - Rank: 4
  - Notes:

- [X] **Hacks GitHub Pages Playground**
  - Rank: 4
  - Notes:

- [X] **Hacks SASS Basics**
  - Rank: 4
  - Notes:

- [X] **Hacks Jupyter Notebook**
  - Rank: 4
  - Notes:

- [X] **Pair Programming**
  - Rank: 4+
  - Notes: tangibles that show co-operative work
 
| Skill | Mastered (Y/N) | Rank (1-4) | Ratio |
| -------- | ------- | -------- | ------- |
|Attendance|Y|4|.90|
|Work Habits|Y|4|.90|
|Behavior|Y|4|.90|
|Timeliness|Y|4|.90|
|Tech Sense|Y|4|.90|
|Tech Talk|Y|4|.90|
|Tech Growth|Y|4|.90|
|Advocacy|Y|4|.90|
|Comm & Collab|Y|4|.90|
|Integrity|Y|4|.90|
|Organized|Y|3|.85|
|Total||43|9.85|
|Average||3.9|.89|

Hacks provided at this URL: https://spooketti.github.io/studentCSA//2024/09/08/checklistSprintOne_IPYNB_2_.html

_Originally posted by @jm1021 in https://github.com/nighthawkcoders/portfolio_2025/issues/14#issuecomment-2237380182_
